{% set name = "sixtools" %}
{% set version = "0.0.3" %}
{% set sha256 = "38950e920b9ae28979f1dee66756763714b601ed1553ec864a8278de6c295105" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "{{ sha256 }}"

build:
  number: 0
  noarch: "python"
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python
    - pip
  run:
    - python
    - databroker
    - ipywidgets
    - matplotlib
    - numpy
    - pandas
    - pims
    - rixs
    - scipy

test:
  imports:
    - sixtools
  requires:
    - pytest
  commands:
    - pytest --pyargs sixtools.tests

about:
  home: "https://github.com/NSLS-II-SIX/sixtools"
  license: "BSD (3-clause)"
  license_family: "BSD"
  license_file: "LICENSE"
  summary: "Software for performing resonant inelastic xray scattering analysis at NSLS-II"
